<?php print_r($this->view->data_usuario); ?>
<section class="busqueda-empresas">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="h1 h1-border-bottom">Búsqueda de Empresas</h1>
                <div class="input-group">
                    <input type="text" placeholder="Número de RUC o Razón Social">
                    <button type="button" class="sp-btn sp-btn-light-blue">Buscar</button>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="rubros-importantes">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="h1 h1-border-bottom">Rubros más Importantes</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="rubros">
                    <div class="bloque">
                        <div class="titulo">Agricolas</div>
                        <div class="cantidad">+ 3500</div>
                    </div>
                    <div class="bloque">
                        <div class="titulo">Agricolas</div>
                        <div class="cantidad">+ 3500</div>
                    </div>
                    <div class="bloque">
                        <div class="titulo">Agricolas</div>
                        <div class="cantidad">+ 3500</div>
                    </div>
                    <div class="bloque">
                        <div class="titulo">Agricolas</div>
                        <div class="cantidad">+ 3500</div>
                    </div>
                    <div class="bloque">
                        <div class="titulo">Agricolas</div>
                        <div class="cantidad">+ 3500</div>
                    </div>
                    <div class="bloque">
                        <div class="titulo">Agricolas</div>
                        <div class="cantidad">+ 3500</div>
                    </div>
                    <div class="bloque">
                        <div class="titulo">Agricolas</div>
                        <div class="cantidad">+ 3500</div>
                    </div>
                    <div class="bloque">
                        <div class="titulo">Agricolas</div>
                        <div class="cantidad">+ 3500</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="empresas-importantes contenedor-empresas">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="h1 h1-border-bottom">Empresas privadas más Importantes</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="empresas">
                    <div class="bloque">
                        <div class="fondo">
                            <div class="icono">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                        <div class="encabezado">Banco de Credito del Perú</div>
                    </div>
                    <div class="bloque">
                        <div class="fondo">
                            <div class="icono">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                        <div class="encabezado">Banco de Credito del Perú</div>
                    </div>
                    <div class="bloque">
                        <div class="fondo">
                            <div class="icono">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                        <div class="encabezado">Banco de Credito del Perú</div>
                    </div>
                    <div class="bloque">
                        <div class="fondo">
                            <div class="icono">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                        <div class="encabezado">Banco de Credito del Perú</div>
                    </div>
                    <div class="bloque">
                        <div class="fondo">
                            <div class="icono">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                        <div class="encabezado">Banco de Credito del Perú</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="boton">
                    <a href="javascript:void(0)" class="sp-btn sp-btn-blue">Empresas con mayor crecimiento</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="empresas-crecimiento-laboral contenedor-empresas">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="h1 h1-border-bottom">Empresas con mayor crecimiento Laboral</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="empresas">
                    <div class="bloque">
                        <div class="fondo">
                            <div class="icono">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                        <div class="encabezado">Banco de Credito del Perú</div>
                    </div>
                    <div class="bloque">
                        <div class="fondo">
                            <div class="icono">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                        <div class="encabezado">Banco de Credito del Perú</div>
                    </div>
                    <div class="bloque">
                        <div class="fondo">
                            <div class="icono">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                        <div class="encabezado">Banco de Credito del Perú</div>
                    </div>
                    <div class="bloque">
                        <div class="fondo">
                            <div class="icono">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                        <div class="encabezado">Banco de Credito del Perú</div>
                    </div>
                    <div class="bloque">
                        <div class="fondo">
                            <div class="icono">
                                <i class="fas fa-plus-circle"></i>
                            </div>
                        </div>
                        <div class="encabezado">Banco de Credito del Perú</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="boton">
                    <a href="javascript:void(0)" class="sp-btn sp-btn-blue">Empresas con mayor crecimiento</a>
                </div>
            </div>
        </div>
    </div>
</section>